/**
 * Even terms in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be 
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four
 * million, find the sum of all even-valued terms.
 */

public class Problem_2 {
    public static void main(String[] args){
        long sum = 0, fib = 0, a = 0, b = 1;
        int stop = 4000000;
        while (fib < stop) {
            fib = a + b;
            if (fib % 2 == 0)
                sum += fib;
            a = b;
            b = fib;
        }

        System.out.println("Sum: " + sum);
    }
}